# Generated by Django 2.1.15 on 2020-04-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='produits',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='produits_sans_prix',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='moteur',
        ),
        migrations.DeleteModel(
            name='Moteur',
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Vendeur',
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
